#!/bin/bash
# ==================================================
#  KoolDots (2026)
#  Project URL: https://github.com/LinuxBeginnings
#  License: GNU GPLv3
#  SPDX-License-Identifier: GPL-3.0-or-later
# ==================================================
# 💫 https://github.com/LinuxBeginnings 💫 #
# hyprsysteminfo #

#specific branch or release (fallback)
tag_default="auto"
if [ -z "${HYPRSYSTEMINFO_TAG:-}" ]; then
  TAGS_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/hypr-tags.env"
  [ -f "$TAGS_FILE" ] && source "$TAGS_FILE"
fi
TAG_SRC="${HYPRSYSTEMINFO_TAG:-$tag_default}"
[[ "$TAG_SRC" =~ ^(auto|latest)$ ]] && git_ref="" || git_ref="$TAG_SRC"

DO_INSTALL=1
[ "$1" = "--dry-run" ] || [ "${DRY_RUN}" = "1" ] || [ "${DRY_RUN}" = "true" ] && { DO_INSTALL=0; echo "${NOTE} DRY RUN: install step will be skipped."; }

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PARENT_DIR="$SCRIPT_DIR/.."
cd "$PARENT_DIR" || exit 1
source "$(dirname "$(readlink -f "$0")")/Global_functions.sh"

LOG="Install-Logs/install-$(date +%d-%H%M%S)_hyprsysteminfo.log"
MLOG="install-$(date +%d-%H%M%S)_hyprsysteminfo2.log"
# Build-time dependencies for hyprsysteminfo
DEPS=(
  libpci-dev
)
printf "\n%s - Installing ${YELLOW}hyprsysteminfo dependencies${RESET} .... \n" "${INFO}"
for PKG in "${DEPS[@]}"; do
  re_install_package "$PKG" 2>&1 | tee -a "$LOG"
  if [ $? -ne 0 ]; then
    echo -e "\e[1A\e[K${ERROR} - ${YELLOW}$PKG${RESET} installation failed; see logs"
    exit 1
  fi
done

SRC_DIR="$SRC_ROOT/hyprsysteminfo"
rm -rf "$SRC_DIR" 2>/dev/null || true
printf "${INFO} Installing ${YELLOW}hyprsysteminfo ${git_ref:-default-branch}${RESET} ...\n"
if git clone --recursive ${git_ref:+-b "$git_ref"} https://github.com/hyprwm/hyprsysteminfo.git "$SRC_DIR"; then
    cd "$SRC_DIR" || exit 1
    BUILD_DIR="$BUILD_ROOT/hyprsysteminfo"
    rm -rf "$BUILD_DIR" && mkdir -p "$BUILD_DIR"
    # Ensure hyprsysteminfo links against libpci via target_link_libraries
    if [ -f "$SRC_DIR/CMakeLists.txt" ]; then
        if ! grep -q "target_link_libraries(hyprsysteminfo pci" "$SRC_DIR/CMakeLists.txt"; then
            sed -ri '/target_link_libraries\\(hyprsysteminfo[[:space:]]+PkgConfig::deps\\)/a target_link_libraries(hyprsysteminfo pci)' "$SRC_DIR/CMakeLists.txt"
        fi
    fi
    # Replace #embed with an autogenerated bytes include for toolchains lacking it
    ICONS_HDR="$SRC_DIR/src/icons/Icons.hpp"
    ICON_SRC="$SRC_DIR/resource/hyprlandlogo.svg"
    ICON_INC="$SRC_DIR/src/icons/hyprlandlogo.bytes.inc"
    if [ -f "$ICONS_HDR" ] && [ -f "$ICON_SRC" ] && grep -q '^[[:space:]]*#embed' "$ICONS_HDR"; then
        if ! command -v xxd >/dev/null 2>&1; then
            echo "${NOTE} xxd not found; attempting to install xxd..." | tee -a "$LOG"
            install_package "xxd" 2>&1 | tee -a "$LOG" || true
        fi
        if command -v xxd >/dev/null 2>&1; then
            TMP_ICON="$(mktemp)"
            xxd -i -g 1 -c 16 "$ICON_SRC" >"$TMP_ICON"
            awk 'BEGIN{f=0}
                {
                    if (f == 1) {
                        if ($0 ~ /^};/) { f=0; next }
                        print; next
                    }
                    if ($0 ~ /{/) {
                        f=1
                        sub(/.*\{/, "")
                        if (length($0) > 0) print
                    }
                }' "$TMP_ICON" >"$ICON_INC"
            rm -f "$TMP_ICON"
            if [ ! -s "$ICON_INC" ]; then
                echo "${NOTE} Generated icon bytes include is empty; check $ICON_SRC" | tee -a "$LOG"
            fi
            # Replace any #embed line in Icons.hpp with the generated include
            sed -ri 's|^[[:space:]]*#embed[[:space:]]+\"[^\"]+\"[[:space:]]*$|#include \"hyprlandlogo.bytes.inc\"|g' "$ICONS_HDR" || true
        else
            echo "${NOTE} xxd still unavailable; skipping #embed replacement." | tee -a "$LOG"
        fi
    fi
    # Ensure pci headers are treated as C when compiling C++
    SYSINFO_CPP="$SRC_DIR/src/utils/SystemInfo.cpp"
    if [ -f "$SYSINFO_CPP" ]; then
        # Clean any previous escaped insertion and re-add with real newlines
        perl -0777 -pi -e 's|extern "C" \\{\\\\n#include <pci/pci.h>\\\\n\\}|\n|g' "$SYSINFO_CPP"
        if grep -q '#include <pci/pci.h>' "$SYSINFO_CPP"; then
            perl -0777 -pi -e 's|#include <pci/pci.h>|extern "C" {\n#include <pci/pci.h>\n}|g' "$SYSINFO_CPP"
        fi
    fi
    BUILD_FAILED=0
    # Ensure libpci is linked even if upstream CMake doesn't add it
    export LDFLAGS="${LDFLAGS:-} -lpci"
    if [ -f CMakeLists.txt ]; then
        if grep -q "WaylandClientPrivate" src/CMakeLists.txt && ! grep -q "WaylandClientPrivate" CMakeLists.txt; then
            echo "${NOTE} Adding Qt6 WaylandClientPrivate component to satisfy Debian Qt6 packaging." | tee -a "$MLOG"
            sed -i 's/WaylandClient)/WaylandClient WaylandClientPrivate)/' CMakeLists.txt
        fi
        cmake -S . -B "$BUILD_DIR" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$INSTALL_PREFIX" -DCMAKE_EXE_LINKER_FLAGS="-lpci" -DCMAKE_SHARED_LINKER_FLAGS="-lpci" -DCMAKE_MODULE_LINKER_FLAGS="-lpci" 2>&1 | tee -a "$MLOG"
        cmake --build "$BUILD_DIR" -j "$(nproc 2>/dev/null || getconf _NPROCESSORS_CONF)" 2>&1 | tee -a "$MLOG"
        build_rc=${PIPESTATUS[0]}
        if [ $build_rc -ne 0 ]; then
            BUILD_FAILED=1
        fi
        if [ $DO_INSTALL -eq 1 ] && [ $BUILD_FAILED -eq 0 ]; then
            $(install_sudo) env $(install_destdir_env) cmake --install "$BUILD_DIR" 2>&1 | tee -a "$MLOG"
        elif [ $DO_INSTALL -eq 1 ]; then
            echo "${ERROR} hyprsysteminfo build failed; skipping install." | tee -a "$MLOG"
        else
            echo "${NOTE} DRY RUN: skip install" | tee -a "$MLOG"
        fi
    elif [ -f meson.build ]; then
        meson setup "$BUILD_DIR" --buildtype=release --prefix="$INSTALL_PREFIX" 2>&1 | tee -a "$MLOG"
        meson compile -C "$BUILD_DIR" 2>&1 | tee -a "$MLOG"
        build_rc=${PIPESTATUS[0]}
        if [ $build_rc -ne 0 ]; then
            BUILD_FAILED=1
        fi
        if [ $DO_INSTALL -eq 1 ] && [ $BUILD_FAILED -eq 0 ]; then
            $(install_sudo) env $(install_destdir_env) meson install -C "$BUILD_DIR" 2>&1 | tee -a "$MLOG"
        elif [ $DO_INSTALL -eq 1 ]; then
            echo "${ERROR} hyprsysteminfo build failed; skipping install." | tee -a "$MLOG"
        else
            echo "${NOTE} DRY RUN: skip install" | tee -a "$MLOG"
        fi
    else
        echo "${ERROR} Unknown build system for hyprsysteminfo" | tee -a "$MLOG"
    fi
    mv "$MLOG" "$PARENT_DIR/Install-Logs/" || true
    if [ "${BUILD_FAILED:-0}" -ne 0 ]; then
        exit 1
    fi
else
    echo -e "${ERROR} Download failed for ${YELLOW}hyprsysteminfo${RESET}" 2>&1 | tee -a "$LOG"
fi
printf "\n%.0s" {1..1}
